/* Stars Coffee — menu content (edit prices and items here)
   كل صنف فيه prices كقائمة. إذا فيه أكثر من سعر، كل سعر مربوط بالحجم
   اللي بنفس الترتيب في sizes. */

const MENU_CURRENCY = "₪";

const MENU_CATEGORIES = [
  {
    id: "coffee",
    ar: "القهوة",
    en: "Coffee",
    items: [
      { ar: "إسبريسو", en: "Espresso", note: "قصير أو طويل", prices: [8] },
      { ar: "إسبريسو دبل", en: "Double Espresso", note: "قصير أو طويل", prices: [10] },
      { ar: "مكياتو", en: "Macchiato", note: "قصير أو طويل", prices: [9] },
      { ar: "لاتيه مكياتو", en: "Latte Macchiato", prices: [12] },
      { ar: "كابتشينو", en: "Cappuccino", sizes: ["صغير", "كبير"], prices: [12, 14] },
      { ar: "أمريكانو", en: "Americano", sizes: ["صغير", "كبير"], prices: [10, 12] },
      { ar: "نس كافيه", en: "Nescafé", sizes: ["صغير", "كبير"], prices: [11, 13] },
      { ar: "فانيلا إيطالي", en: "Italian Vanilla", prices: [14] },
      { ar: "فرينش فانيلا", en: "French Vanilla", prices: [16] },
      { ar: "موكا", en: "Mocha", prices: [16] },
      { ar: "قهوة سوداء", en: "Black Coffee", prices: [10] },
      { ar: "أفوغاتو", en: "Affogato", note: "كرة بوظة مع جرعة إسبريسو", prices: [14] },
    ],
  },
  {
    id: "hot-drinks",
    ar: "مشروبات ساخنة",
    en: "Hot Drinks",
    items: [
      { ar: "شوكو ساخن", en: "Hot Chocolate", sizes: ["صغير", "كبير"], prices: [11, 13] },
      { ar: "شوكولاتة ساخنة فاخرة", en: "Premium Hot Chocolate", prices: [18] },
      { ar: "سحلب", en: "Sahlab", prices: [15] },
    ],
  },
  {
    id: "tea",
    ar: "شاي",
    en: "Tea",
    items: [
      { ar: "شاي", en: "Tea", prices: [10] },
      { ar: "شاي بالنعنع", en: "Mint Tea", prices: [13] },
      { ar: "شاي ليمون وليزا", en: "Lemon Verbena Tea", prices: [13] },
      { ar: "شاي توت بري", en: "Wild Berry Tea", prices: [13] },
      {
        ar: "شاي منعش",
        en: "Refreshing Tea",
        note: "عيدان قرفة، زنجبيل، ميرمية، ليمون، عسل",
        prices: [16],
      },
    ],
  },
  {
    id: "cold-drinks",
    ar: "مشروبات باردة",
    en: "Cold Drinks",
    items: [
      { ar: "شاي بارد", en: "Iced Tea", sizes: ["صغير", "وسط", "كبير"], prices: [13, 15, 18] },
      { ar: "شوكو بارد", en: "Iced Chocolate", sizes: ["صغير", "وسط", "كبير"], prices: [13, 15, 17] },
      { ar: "أمريكانو بارد", en: "Iced Americano", sizes: ["صغير", "وسط", "كبير"], prices: [10, 12, 14] },
      { ar: "قهوة باردة", en: "Iced Coffee", sizes: ["صغير", "وسط", "كبير"], prices: [13, 15, 18] },
      { ar: "آيس بيكان", en: "Iced Pecan", sizes: ["صغير", "وسط", "كبير"], prices: [16, 18, 20] },
      { ar: "آيس كافيه", en: "Ice Café", sizes: ["صغير", "وسط", "كبير"], prices: [12, 14, 16] },
      { ar: "ليمون ونعنع مثلّج", en: "Frozen Mint Lemonade", sizes: ["صغير", "وسط", "كبير"], prices: [18, 20, 22] },
      { ar: "ليمونادا", en: "Lemonade", sizes: ["صغير", "وسط", "كبير"], prices: [12, 14, 16] },
      { ar: "آيس بطيخ", en: "Iced Watermelon", sizes: ["صغير", "وسط", "كبير"], prices: [12, 14, 16] },
      {
        ar: "ريد هولك",
        en: "Red Hulk",
        note: "مشروب طاقة، ثلج، جيلي، سكاكر، سيروب بطيخ",
        prices: [20],
      },
      {
        ar: "ستارز هولك",
        en: "Stars Hulk",
        note: "مشروب طاقة، ثلج، جيلي، سكاكر، سيروب شمام",
        prices: [20],
      },
    ],
  },
  {
    id: "mojito",
    ar: "موهيتو",
    en: "Mojito",
    note: "سعر موحد لكل النكهات. القاعدة حسب الاختيار.",
    bases: ["سبرايت", "إكس إل", "صودا", "بلو دي"],
    flatPrice: 24,
    items: [
      { ar: "جريب فروت وردي", en: "Pink Grapefruit" },
      { ar: "برتقال", en: "Orange" },
      { ar: "ليمون ونعنع", en: "Mint Lemon" },
      { ar: "ليمون", en: "Lemon" },
      { ar: "رمان", en: "Pomegranate" },
      { ar: "أناناس", en: "Pineapple" },
      { ar: "بطيخ", en: "Watermelon" },
      { ar: "مانجا", en: "Mango" },
      { ar: "ليتشي", en: "Lychee" },
      { ar: "جوز الهند", en: "Coconut" },
      { ar: "فراولة", en: "Strawberry" },
      { ar: "خوخ", en: "Peach" },
      { ar: "باشن فروت", en: "Passion Fruit" },
      { ar: "لافندر", en: "Lavender" },
      { ar: "توت بري (غرينادين)", en: "Grenadine" },
      { ar: "توت أسود", en: "Blackberry" },
      { ar: "علكة", en: "Gum" },
      { ar: "بلو بيري", en: "Blueberry" },
    ],
  },
  {
    id: "milkshake",
    ar: "ميلك شيك",
    en: "Milkshake",
    note: "المكونات: بوظة، حليب، كريما، إضافة",
    items: [
      { ar: "سنيكرز", en: "Snickers", sizes: ["صغير", "وسط", "كبير"], prices: [22, 25, 28] },
      { ar: "أوريو", en: "Oreo", sizes: ["صغير", "وسط", "كبير"], prices: [22, 25, 28] },
      { ar: "فانيلا", en: "Vanilla", sizes: ["صغير", "وسط", "كبير"], prices: [22, 25, 28] },
      { ar: "شوكولاتة", en: "Chocolate", sizes: ["صغير", "وسط", "كبير"], prices: [22, 25, 28] },
      { ar: "توت بري", en: "Wild Berry", sizes: ["صغير", "وسط", "كبير"], prices: [22, 25, 28] },
      { ar: "بزوكا", en: "Bazooka", sizes: ["صغير", "وسط", "كبير"], prices: [22, 25, 28] },
      { ar: "فيريرو روشيه", en: "Ferrero Rocher", sizes: ["صغير", "وسط", "كبير"], prices: [22, 25, 28] },
      { ar: "لوتس", en: "Lotus", sizes: ["صغير", "وسط", "كبير"], prices: [22, 25, 28] },
      { ar: "فراولة", en: "Strawberry", sizes: ["صغير", "وسط", "كبير"], prices: [22, 25, 28] },
      {
        ar: "آينشتاين",
        en: "Einstein",
        note: "خلطة خاصة مع كريما ومارشميلو",
        sizes: ["صغير", "وسط", "كبير"],
        prices: [25, 28, 30],
      },
      {
        ar: "هافانا",
        en: "Havana",
        note: "بوظة تريكس مع كورن فليكس",
        sizes: ["صغير", "وسط", "كبير"],
        prices: [25, 28, 30],
      },
      { ar: "فستق", en: "Pistachio", sizes: ["صغير", "وسط", "كبير"], prices: [25, 28, 30] },
      { ar: "الأسطورة", en: "Legend", sizes: ["صغير", "وسط", "كبير"], prices: [25, 28, 30] },
      { ar: "كيندر", en: "Kinder", sizes: ["صغير", "وسط", "كبير"], prices: [25, 28, 30] },
      { ar: "نوتيلا", en: "Nutella", sizes: ["صغير", "وسط", "كبير"], prices: [25, 28, 30] },
    ],
  },
  {
    id: "fruit-shake",
    ar: "فروت شيك",
    en: "Fruit Shake",
    note: "فواكه مع اختيار: حليب، برتقال، أو عنب",
    items: [
      { ar: "توت بري", en: "Wild Berry", sizes: ["صغير", "وسط", "كبير"], prices: [22, 24, 26] },
      { ar: "مانجو", en: "Mango", sizes: ["صغير", "وسط", "كبير"], prices: [22, 24, 26] },
      { ar: "فراولة", en: "Strawberry", sizes: ["صغير", "وسط", "كبير"], prices: [22, 24, 26] },
      { ar: "كيوي", en: "Kiwi", sizes: ["صغير", "وسط", "كبير"], prices: [24, 26, 28] },
      { ar: "أناناس", en: "Pineapple", sizes: ["صغير", "وسط", "كبير"], prices: [22, 24, 26] },
      { ar: "تمر", en: "Dates", sizes: ["صغير", "وسط", "كبير"], prices: [22, 24, 26] },
      { ar: "موز", en: "Banana", sizes: ["صغير", "وسط", "كبير"], prices: [22, 24, 26] },
    ],
  },
  {
    id: "fresh-juices",
    ar: "عصائر طبيعية",
    en: "Fresh Juices",
    items: [
      { ar: "برتقال", en: "Orange", sizes: ["صغير", "وسط", "كبير"], prices: [15, 18, 20] },
      { ar: "جزر", en: "Carrot", sizes: ["صغير", "وسط", "كبير"], prices: [15, 18, 20] },
      { ar: "تفاح", en: "Apple", sizes: ["صغير", "وسط", "كبير"], prices: [15, 18, 20] },
    ],
  },
  {
    id: "soft-drinks",
    ar: "مشروبات خفيفة",
    en: "Soft Drinks",
    items: [
      { ar: "كوكاكولا", en: "Coca-Cola", note: "علبة أو زجاجة", prices: [8] },
      { ar: "كوكاكولا زيرو", en: "Coca-Cola Zero", prices: [8] },
      { ar: "إكس إل", en: "XL", prices: [8] },
      { ar: "صودا", en: "Soda", prices: [7] },
      { ar: "مياه معدنية", en: "Mineral Water", prices: [7] },
    ],
  },
  {
    id: "crepe",
    ar: "كريب",
    en: "Crepe",
    items: [
      { ar: "كريب نوتيلا", en: "Nutella Crepe", prices: [24] },
      { ar: "كريب لوتس", en: "Lotus Crepe", prices: [26] },
      { ar: "كريب فستق", en: "Pistachio Crepe", prices: [28] },
      { ar: "كريب كيندر", en: "Kinder Crepe", prices: [28] },
      { ar: "كريب مع بوظة", en: "Crepe with Ice Cream", prices: [34] },
    ],
  },
  {
    id: "waffle",
    ar: "وافل بلجيكي",
    en: "Belgian Waffle",
    note: "نصف وجبة: وافل مع كرة بوظة وكريما. وجبة كاملة: قطعتين وافل مع كرتين بوظة وكريما",
    items: [
      { ar: "وافل بلجيكي نوتيلا", en: "Nutella Waffle", sizes: ["نصف وجبة", "وجبة كاملة"], prices: [30, 55] },
      { ar: "وافل بلجيكي لوتس", en: "Lotus Waffle", sizes: ["نصف وجبة", "وجبة كاملة"], prices: [33, 58] },
      { ar: "وافل بلجيكي كيندر", en: "Kinder Waffle", sizes: ["نصف وجبة", "وجبة كاملة"], prices: [35, 60] },
      { ar: "وافل بلجيكي فستق", en: "Pistachio Waffle", sizes: ["نصف وجبة", "وجبة كاملة"], prices: [35, 60] },
    ],
  },
  {
    id: "pancake-puffs",
    ar: "فشافيش",
    en: "Pancake Puffs",
    items: [
      { ar: "فشافيش نوتيلا", en: "Nutella Puffs", sizes: ["6 قطع", "12 قطعة"], prices: [14, 24] },
      { ar: "فشافيش لوتس", en: "Lotus Puffs", sizes: ["6 قطع", "12 قطعة"], prices: [15, 26] },
      { ar: "فشافيش كيندر", en: "Kinder Puffs", sizes: ["6 قطع", "12 قطعة"], prices: [16, 28] },
      { ar: "فشافيش فستق", en: "Pistachio Puffs", sizes: ["6 قطع", "12 قطعة"], prices: [16, 28] },
    ],
  },
  {
    id: "cakes",
    ar: "كعك",
    en: "Cakes",
    note: "يُقدَّم مع بوظة وكريما",
    items: [
      { ar: "كعكة الشوكولاتة الساخنة", en: "Chocolate Soufflé", prices: [34] },
      { ar: "كعكة الجبنة", en: "Crumble Cheesecake", prices: [34] },
      { ar: "كعكة ريد فيلفيت", en: "Red Velvet Cake", prices: [34] },
    ],
  },
  {
    id: "special-desserts",
    ar: "حلويات خاصة",
    en: "Special Desserts",
    items: [
      { ar: "تشوروز", en: "Churros", note: "6 قطع", prices: [30] },
      { ar: "سوشي بالشوكولاتة", en: "Chocolate Sushi", note: "6 قطع", prices: [28] },
      {
        ar: "وجبة ستارز كومبو",
        en: "Stars Combo",
        note: "قطعتين وافل بلجيكي، 8 فشافيش، كريب، 4 تشوروز، مع كرتين بوظة وكريما",
        prices: [130],
      },
    ],
  },
  {
    id: "croissant",
    ar: "كرواسون",
    en: "Croissant",
    items: [
      { ar: "كرواسون", en: "Butter Croissant", prices: [12] },
      { ar: "كرواسون بالشوكولاتة", en: "Chocolate Croissant", prices: [14] },
      { ar: "كرواسون باللوز", en: "Almond Croissant", prices: [14] },
      { ar: "كرواسون مع بوظة", en: "Croissant with Ice Cream", prices: [20] },
    ],
  },
  {
    id: "ice-cream",
    ar: "بوظة",
    en: "Ice Cream",
    items: [
      { ar: "كرة بوظة", en: "One Scoop", prices: [10] },
      { ar: "كرتين بوظة", en: "Two Scoops", prices: [18] },
      { ar: "3 كرات بوظة", en: "Three Scoops", prices: [24] },
      { ar: "نصف كيلو بوظة", en: "Half Kilo", prices: [45] },
      { ar: "كيلو بوظة", en: "One Kilo", prices: [75] },
    ],
  },
  {
    id: "coffee-and-more",
    ar: "قهوة وأكثر",
    en: "Coffee & More",
    items: [
      { ar: "قهوة وكرواسون", en: "Coffee & Croissant", prices: [18] },
      { ar: "قهوة وكعكة", en: "Coffee & Cake", prices: [35] },
    ],
  },
];
